name: 'CI'

on:
  push:
  workflow_dispatch:

jobs:
  job-run-files-all:
    name: 'Run files'
    runs-on: ubuntu-latest
    steps:
      - name: 'Install extra packages'
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get install -y --no-install-recommends pax-utils qemu-user
      - name: 'Check out code'
        uses: actions/checkout@v3
        with: { submodules: true }
      - name: 'Run'
        run: |
          bash ./run_files.sh ./files/all

# vim:set ts=2 sw=2 et:
